services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:5000"
    networks:
      - final_network

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=tms_db
      - POSTGRES_USER=tms_user
      - POSTGRES_PASSWORD=tms_pass
    volumes:
      - pgdata:/var/lib/postgres/data
    networks:
      - final_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "tms_user", "-d", "tms_db"]
      interval: 10s
      retries: 5

  app:
    build:
      context: ./frontend-new
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - final_network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - final_network
volumes:
  pgdata:

networks:
  final_network:
    driver: bridge